defaults:
  - topology: 20250822A
  - descriptors: 20250822A
  - _self_
label:
  network: apelp
  date: !!str 20250822
  batch: A
  scheme: prhd
synthesis:
  max_try: 500
multiprocessing:
  cpu_num: 8