batch_size: 16
n_epochs: 100
n_epochs_per_anneal_cycle: 10
rampup_anneal_cycle_ratio: 0.5
max_beta: 0.1
lr: 1e-4
weight_decay: 1e-5
loss_log_batch_indx: 100
clip_norm_max: 20.0
patience: 10
min_delta_prop: 0.02