batch_size: 16
n_epochs: 2 # 1000
n_epochs_per_anneal_cycle: 10
rampup_anneal_cycle_ratio: 0.5
max_beta: 0.005
lr: 1e-4
weight_decay: 1e-5
lr_scheduler_mode: min
lr_scheduler_factor: 0.5
lr_scheduler_patience: 10
loss_log_batch_indx: 100
clip_norm_max: 20.0
patience: 15